### ISSUE TITLE
i get this error how to resolve it thank you

### ISSUE THREAD

**Issue by Tarikkassy** [algphello/android_device_honor_7a#1]
Which would you like? [aosp_arm-eng] 8
build/core/product_config.mk:243: *** _nic.PRODUCTS.[[device/honor/AUML29//omni_AUML29.mk]]: "device/honor/AUML29//omni_AUML29.mk" does not exist.  Arresto.
Your device can't be found in device sources..
Traceback (most recent call last):
  File "vendor/omni/build/tools/roomservice.py", line 355, in <module>
    fetch_device(device)
  File "vendor/omni/build/tools/roomservice.py", line 323, in fetch_device
    git_data = search_gerrit_for_device(device)
  File "vendor/omni/build/tools/roomservice.py", line 81, in search_gerrit_for_device
    device_data = check_repo_exists(git_data, device)
  File "vendor/omni/build/tools/roomservice.py", line 58, in check_repo_exists
    "exiting roomservice".format(device=device))
Exception: AUML29 not found,exiting roomservice
build/core/product_config.mk:243: *** _nic.PRODUCTS.[[device/honor/AUML29//omni_AUML29.mk]]: "device/honor/AUML29//omni_AUML29.mk" does not exist.  Arresto.

** Don't have a product spec for: 'omni_AUML29'
** Do you have the right repo manifest?

**Comment by algphello** [comment]
i try to re-build a new tree

**Comment by Tarikkassy** [comment]
i soved the problem and i build twrp but not booting when i flash it in my honor 7a,

i have a question how to build tree

**Comment by algphello** [comment]
@Tarikkassy you can use this https://github.com/algphello/android_device_honor_msm8937_64 as tree

**Comment by Tarikkassy** [comment]
touch screen not work with this tree

**Comment by algphello** [comment]
noop touch is working fine, screen shot is not work

**Comment by Tarikkassy** [comment]
honor version android 8.0  aum-l29 7a is the sime?

**Comment by algphello** [comment]
this is for aum-l29

**Comment by Tarikkassy** [comment]
have you a lineage os device tree for aum-l29 honor please sand me the link
